version: "3" 
services:
  nginx:
    image: nginx:latest
    volumes:
      - "./projects:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    build:
      context: ./php
    volumes:
      - "./projects:/var/www/html"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    links:
      - mysql
  
  mysql:
    image: mysql:5.7.20
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rondon

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
